server.port=8080
spring.application.name=demo-string-concat-vs-stringbuilder

# Désactive l'auto-configuration du banner et des logs inutiles pour les tests de charge
spring.main.banner-mode=off
logging.level.root=WARN
logging.level.com.example.demo=INFO
